### ISSUE TITLE
difference in lat/lon dimensions in cf.describe() after subtracting arrays

### ISSUE THREAD

**Issue by allibco** [xarray-contrib/cf-xarray#124]
Another question that I can't seem to sort out. I have two data arrays that I want to subtract.  But after I subtract them, there are two choices for lat and lon instead of just 1 like in the data arrays before I subtract.

![p1](https://user-images.githubusercontent.com/14944423/105554283-3eb00300-5cc4-11eb-9b08-f4df3f4ec312.png)
![p2](https://user-images.githubusercontent.com/14944423/105554302-4a032e80-5cc4-11eb-9af3-4fddebc4dcb5.png)

The problem comes about when I want the longitude of dd:
![p3](https://user-images.githubusercontent.com/14944423/105554334-5b4c3b00-5cc4-11eb-9f82-69ad9af21ec4.png)

Any suggestions are appreciated! Thank you!

**Comment by aulemahal** [comment]
Hi again!

As a side note before I answer: it would be more efficient if you submitted what is called "minimal working examples" when raising an issue. By that I mean copy-pastable code that would reproduce the issue (and not, or in addition to, images). I concede that when using special data, that might be difficult, but it really simplifies our debugging work when trying to answer.
But you were lucky, I think I know the problem because I recognize the type of data.

As you may have noticed, `da.cf.describe()` only shows 'TLONG', 'TLAT' as coordinates, even if 'ULONG' and 'ULAT' are listed in the `coords`attributes. This should be due to the `da.attrs['coordinates']` attribute (even if I don't see it from your screenshots). If tells `cf_xarray` which coordinates are to be used (and then listed in `cf.describe()`).

However, by default, xarray **removes** all attributes when dataarrays are operated on. Thus, the result of the subtraction, `dd`, doesn't have the `'coordinates'` attribute and `cf` can't decide which coordinate pair to use : it shows both.

A fix would be to set xarray's `keep_attrs` option:
```python3
import xarray as xr

# 1st option, set it globally, impacting all further computations:
xr.set_options(keep_attrs=True)

# 2nd option, set it within a context, only the computation inside it are altered:
with xr.set_options(keep_attrs=True):
    dd  = da2 - da2 
```
With either option, `dd` should have kept the `'coordinates' ` attribute and `cf` should only show the corresponding coordinate pair.

Hope that helps!

**Comment by allibco** [comment]
Thanks so much for that explanation - that makes sense now, and I have a better understanding of what's going on.   Next time I will submit a copy-pasteable simple code :)  Thanks again!

**Comment by allibco** [comment]
Also thanks for replying so promptly!

**Comment by allibco** [comment]
Just following up as it turns out that I did not have any coordinates in the data array attributes for da1 and da2.
However, your explanation did set me on the right path.  I looked through your introductory example again (before bugging you this time), and I was able to get it to work by doing (as in [110] above):
 
`da = pop0.cf["SST"]
`
instead of 

`da = pop0["SST"]
`
(and leaving everything else the same). 

So now I can move on to the next thing :). I appreciate your help.  I have code that works well with atmosphere data and I am attempting to modify it to work with either atmosphere or ocean data - which is why I started using cf_xarray (thanks to @andersy005)
