### ISSUE TITLE
should 'X', 'Y' be synonyms for 'longitude', 'latitude'?

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#23]
I am very unsure about this. Originally, they were synonyms. In 21c03876e1fba1aa94197dbf8c9ff1a8ffc955af I undid that.

Here is the current state of affairs
https://github.com/xarray-contrib/cf-xarray/blob/21c03876e1fba1aa94197dbf8c9ff1a8ffc955af/cf_xarray/accessor.py#L24-L89

Note that `'Z', 'T'` are synonymous with `'vertical', 'time'`.

This would be a good place for someone to chime in.

**Comment by jthielen** [comment]
Based on what we've found in MetPy and in my own frequent use-case of gridded atmospheric data in projected spaces, I would argue that 'X', 'Y' should not be synonyms for 'longitude', 'latitude' in general. It is not uncommon that an 'X'/'Y' axis is present as a coordinate variable (CF terminology)/dimension coordinate (xarray terminology), but they are not 'longitude'/'latitude' (which is instead a 2D auxiliary coordinate variable/non-dimension coordinate). Both these types of coordinates are separately useful, and so, should ideally be available independently (although, in the special case of the plate carrée/`latitude_longitude` projection, they would be synonyms). The [Independent Latitude, Longitude, Vertical, and Time Axes](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_independent_latitude_longitude_vertical_and_time_axes) and [Two-Dimensional Latitude, Longitude, Coordinate Variables](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_two_dimensional_latitude_longitude_coordinate_variables) examples in the CF Conventions were most helpful for me in interpreting these. Elsewhere in the conventions, it at times seems implied that axes of 'X', 'Y' *are* synonyms for 'longitude', 'latitude', but that is clearly not the case based on these two examples. I wish the conventions were clearer in regards to these non-longitude/latitude horizontal coordinate variables/dimension coordinates.

For some background, these were quasi-synonymous in MetPy (i.e. 'X' could access 'longitude' even if >1D, but would default to a suitable dimension coordinate if present), but that was changed with https://github.com/Unidata/MetPy/issues/1090 / https://github.com/Unidata/MetPy/pull/1236. I've been quite happy with how MetPy's been handling it since the change.

**Comment by dcherian** [comment]
Thanks for taking the time to comment @jthielen .

I agree with the reasoning you outlined. I'll keep the issue open for visibility.

**Comment by jthielen** [comment]
> I agree with the reasoning you outlined. I'll keep the issue open for visibility.

@dcherian Sounds great, thanks! In writing up my comment, I was stuck by the difference in terminology between xarray and the CF conventions, so I also just submitted an issue for a doc page that may be worth considering (https://github.com/xarray-contrib/cf-xarray/issues/25). I would be able to help with that at some point, but perhaps not immediately.

**Comment by snowman2** [comment]
This may be useful to have for reference: https://github.com/cf-convention/cf-conventions/pull/133

**Comment by snowman2** [comment]
Also related: https://github.com/pyproj4/pyproj/issues/536
