### ISSUE TITLE
Some time netcdf attributes are not available at `dataset.cf['T'].attrs`

### ISSUE THREAD

**Issue by BorjaEst** [xarray-contrib/cf-xarray#277]
# To reproduce

Get example data from cf-python (for example):
```bash
wget -O temp.zip https://ncas-cms.github.io/cf-python/_downloads/cf_tutorial_files.zip
unzip -o temp.zip
rm temp.zip
```
Dump example to analyse:
```bash
$ ncdump -h air_temperature.nc
netcdf air_temperature {
dimensions:
	time = 2 ;
	...
variables:
	double time_bnds(time, bounds2) ;
	double time(time) ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
		time:units = "days since 1860-1-1" ;   <= This field is present
		time:calendar = "360_day" ;            <= This field is present
		time:axis = "T" ;
		time:bounds = "time_bnds" ;
	...
// global attributes:
		:Conventions = "CF-1.7" ;
```
Open with xarray and cf_xarray
```py
ds = xr.open_dataset("air_temperature.nc")
ds.cf['T'].attrs # No units!
#{'axis': 'T',
# 'bounds': 'time_bnds',
# 'long_name': 'time',
# 'standard_name': 'time'}
```
Maybe this is also a xarray issue as:
```py
ds.time.attrs # No units as well
#{'axis': 'T',
# 'bounds': 'time_bnds',
# 'long_name': 'time',
# 'standard_name': 'time'}
```
I wonder how "time:units" is stored in the netcdf file.

**Comment by malmans2** [comment]
Hi there,
`xarray` decodes time variables converting them to datetime64 objects (i.e., the units attribute does not appear because it's embedded in the datetime64 object).
If you try to re-write the netcdf using `to_netcdf`, you'll see that the units attribute is preserved correctly.

If you prefer working with regular variables rather than datetime64, you can avoid decoding time variables:
```python
ds = xr.open_dataset("air_temperature.nc", decode_times=False)
ds.cf['T'].attrs # With units!
```
```
{'long_name': 'time',
 'standard_name': 'time',
 'units': 'days since 1860-1-1',
 'calendar': '360_day',
 'axis': 'T',
 'bounds': 'time_bnds'}
```
(Although it involves CF attributes, I think this is a question for `xarray` and [this section](https://numpy.org/doc/stable/reference/arrays.datetime.html) of the documentation might help)

**Comment by dcherian** [comment]
You can look at `.encoding` to find attrs during the decoding prices

**Comment by BorjaEst** [comment]
Thank you! Very useful information. I am closing the issue.
