### ISSUE TITLE
Actually decode CF axis attributes

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cf-xarray#3]
Port code from `metpy` to replace this
https://github.com/xarray-contrib/cf-xarray/blob/d3b45ae578fc1510f276eb4d549a18b0b5c503ec/cf_xarray/accessor.py#L20-L21

@jthielen would you have time to do this? I got lost in all the caching and indirection in metpy's code. :P

**Comment by jthielen** [comment]
I would be glad to help (and good to see a repo getting set up)! Though, these next couple weeks are especially hectic with my research tasks and helping to get MetPy 1.0 wrapped up. So, I don't think I'd get the chance to do so immediately, but if you're okay with postponing for a couple weeks, I should be able to. Otherwise, I would completely understand if someone else needed to care of it due to urgency.

**Comment by dcherian** [comment]
No worries! I'll hack something together tomorrow.
